package repository

// This file will be regenerated by sqlc.
// For now, it serves as a placeholder.

import (
	"context"
	"database/sql"
)

// User represents a user in the database
type User struct {
	ID         int64
	TelegramID int64
	Username   sql.NullString
	FirstName  string
	LastName   sql.NullString
	LanguageCode sql.NullString
	IsAdmin    int
	CreatedAt  string
	UpdatedAt  string
}

// Session represents a session in the database
type Session struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt string
	CreatedAt string
}

// Querier is the interface for all query methods
type Querier interface {
	GetUserByTelegramID(ctx context.Context, telegramID int64) (*User, error)
	GetUserByID(ctx context.Context, id int64) (*User, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error)
	GetSessionByToken(ctx context.Context, token string) (*Session, error)
	DeleteExpiredSessions(ctx context.Context) error
}

// CreateUserParams contains parameters for CreateUser
type CreateUserParams struct {
	TelegramID   int64
	Username     sql.NullString
	FirstName    string
	LastName     sql.NullString
	LanguageCode sql.NullString
}

// UpdateUserParams contains parameters for UpdateUser
type UpdateUserParams struct {
	Username     sql.NullString
	FirstName    string
	LastName     sql.NullString
	LanguageCode sql.NullString
	ID           int64
}

// ListUsersParams contains parameters for ListUsers
type ListUsersParams struct {
	Limit  int
	Offset int
}

// CreateSessionParams contains parameters for CreateSession
type CreateSessionParams struct {
	UserID    int64
	Token     string
	ExpiresAt string
}
